### ISSUE TITLE
Some link underlines 1px high, some 2px

### ISSUE THREAD

**Issue by florianbrinkmann** [smashingmagazine/redesign#137]
Hi!

On Firefox 52.0.1 on Windows 10, the link background size of 100% 1.5px leads to some links having a 1px underline and some having a 2px underline.

![link-underline-smashingmagazine](https://cloud.githubusercontent.com/assets/2310924/24091709/01db26f8-0d4a-11e7-8620-a4a41e19200a.png)

**Comment by vitalyfriedman** [comment]
Interesting @FlorianBrinkmann — wondering why it happens. Will look into it!

**Comment by charakterziffer** [comment]
Maybe the reason is that the underline thickness is defined as 1.5px. So sometimes it’s rendered as 1px, sometimes as 2px – in the CSS: `a { background-size: 100% 1.5px; }`. I’d also give the underline a little bit more distance to the text, so instead of `a { background-position: center bottom 29% }` maybe `a { background-position: center bottom 26% }` – but that depends heavily on the displayed font (for me at the moment Georgia) and the rendering of the OS.

**Comment by indysigner** [comment]
Yeah, the link underline value was set to 1.5px —  I set this to 1px just a few days ago. Many thanks for reporting it! @florianbrinkmann
