### ISSUE TITLE
Article format is hard to focus and read

### ISSUE THREAD

**Issue by Vheissu** [smashingmagazine/redesign#151]
Nice work on the redesign, team. However, the new design for articles needs a complete rethink. Not sure what you were going for, but the constrained inner container with content and right sidebar on my 27" monitor is hard to read.

From a UX perspective, see the below image to further explain my point:

![image](https://cloud.githubusercontent.com/assets/368330/24090665/084acedc-0d8e-11e7-83f2-5d853a2ba518.png)

There is a wall of text. You have the author bio, you have the headline, the start of the content weirdly starting half way through the headline. My eyes don't know where to look. I get what you were trying to do with the design and make it read in more of a magazine/book editorial format, but it's quite a lot of visual overload.

The sidebar seems to be too close to the content as well. I'd love to see the old design here where the container was the full width of the page. On my 27" monitor there is a bit of unused space. I like whitespace, but I think there might be too much in this instance.

**Comment by JSeligsohn** [comment]
I'll add that on a large display, since you're using VW to determine the letter spacing, it becomes too spread out, feeling stretched.

**Comment by luboskmetko** [comment]
I think this article layout is an interesting experiment but for me it doesn't work. 

- as others say there is too much going on, too many elements competing for the user's attention at the beginning
- offsetting the main content column to the left ... it's like the form dictates function - because of how elements are formed at the beginning of the article, you are forced to look to the side for the rest of the article which can be 9/10 of the article length in some cases
- I'm wondering why this magazine layout doesn't work on desktop - my theory is that with print magazine (just holding a net issue in my hands), you can hold and move the magazine with the hands so the content you are interested in is right in front of the eyes and the rest is out of focus. Of course, you can also move your head to focus on something but you can easily change the distance of the content from your eyes if needed. This isn't very well doable on desktop.

Just my 2 cents, I won't blame if you stick to your new layout :)

**Comment by indysigner** [comment]
Thanks for bringing it up @Vheissu, @JSeligsohn, and @luboskmetko. Good input! We'll continue the discussion via https://github.com/smashingmagazine/redesign/issues/96
