### ISSUE TITLE
Please revert-back to the old UI

### ISSUE THREAD

**Issue by ux-leap** [smashingmagazine/redesign#322]
Hi Guys,

Your new UI has loads of bugs and has not been received well by many. Could you add a button to revert back to the old UI and measure how many people chooses to do so. Your current UI a design first approach is pushing me and my colleges to the alternative bloging sites or read yours via RSS reader or chrome extension. 

Thanks

**Comment by vitalyfriedman** [comment]
Thanks for your feedback, @rafal-leap — while we are working on refinements, perhaps you could use the "old-style" list of articles on www.smashingmagazine.com/articles/? It should be a good enough fallback, isn't it?..

**Comment by jaxatto** [comment]
Vitaly, could you consider having a place for user feedback rather than just letting users report bugs? You have a lot of wonderful designers who visit your site and I'm sure their feedback would be worthwhile. 

It feels like you've focused entirely on mobile and forgone any focus on your desktop users, with the odd misaligned article titles and distracting two column layout in your articles. I'd love to hear how you're taking user feedback and working on highly reported issues.

**Comment by vitalyfriedman** [comment]
Dear @jaxatto — oh, we are very thankful for all suggestions, and that's why we encourage everybody to submit enhancements and improvements here as well using labels. So we'd love to hear your thoughts, of course. 

I've made it my tradition to run a usability session every day, and there are a few things we are exploring this very moment. One of them is moving away towards one-column layout, as you can see here: https://www.smashingmagazine.com/2017/12/designers-copyright-law-essentials/, and removing the sidebar altogether, but we need to test it first. 

Please note that we are a very small team, and at this point it's just me making design adjustments. I would love to hear your thoughts, and I could definitely use your perspective to improve things. Any feedback would be much appreciated! @jaxatto 

If you could open up a new GitHub issue for the critical suggestions, it would be fantastic!

**Comment by jaxatto** [comment]
Thank you for the quick response, I'm glad to hear you take user feedback very seriously. I love my daily visit to Smashing Magazine and appreciate your team's work to provide an awesome user experience. If you think it'd help, I'll add some comments in a ticket soon. :)
